# --- Motor Gráfico ---
backend = "glx";
glx-no-stencil = true;
glx-copy-from-front = false;

# --- Esquinas Redondeadas ---
corner-radius = 12;
rounded-corners-exclude = [
  "window_type = 'dock'",
  "class_g = 'Polybar'"
];

# --- Transparencia Global ---
active-opacity = 1.0;
inactive-opacity = 0.90;
frame-opacity = 1.0;
inactive-dim = 0.3; 

# --- Reglas específicas de opacidad (Terminal Kitty) ---
opacity-rule = [
  "92:class_g = 'kitty' && focused",
  "80:class_g = 'kitty' && !focused"
];

# --- Efecto de Desenfoque (Cristal Esmerilado) ---
blur-method = "dual_kawase";
blur-strength = 6;
blur-background = true;

blur-background-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "_GTK_FRAME_EXTENTS@:c"
];
