[colors]
bg = #D9222330
bg-solid = #222330
fg = #cef3ff
amarillo = #f0fa8b
orange = #E06C75
gray = #888888
green = #98C379

[bar/main]
width = 100%
height = 36
radius = 12
fixed-center = true

border-left-size = 40
border-right-size = 40
border-top-size = 10
border-color = #00000000

background = ${colors.bg}
foreground = ${colors.fg}

padding-left = 3
padding-right = 3
module-margin = 2

font-0 = "JetBrainsMono Nerd Font:weight=bold:size=10;3"
font-1 = "JetBrainsMono Nerd Font:size=14;4"
font-2 = "JetBrainsMono Nerd Font:size=16;4"

modules-left = i3
modules-center = date
modules-right = wlan sys-expand battery

; =======================================
;                MÓDULOS
; =======================================
[module/arch]
type = custom/text
content = "󰣇 "
content-foreground = ${colors.fg}
content-padding = 1

[module/i3]
type = internal/i3
format = <label-state>

; 󰮯 es el Pacman de Nerd Fonts
label-focused = 󰮯
label-focused-padding = 1
label-focused-foreground = ${colors.amarillo}
label-focused-font = 3

; Círculos vacíos para los demás
label-unfocused = 
label-unfocused-padding = 1
label-unfocused-foreground = ${colors.gray}

label-visible = 
label-visible-padding = 1
label-visible-foreground = ${colors.gray}

[module/date]
type = internal/date
interval = 5
time = "  %I:%M %p"
label = %time%
label-foreground = ${colors.fg}

; --- NUEVO: MÓDULO INTERACTIVO DE RECURSOS ---
[module/sys-expand]
type = custom/script
exec = ~/.config/polybar/sys-info.sh
interval = 2

; Al hacer clic, crea o destruye la bandera que el script lee
click-left = if [ -f /tmp/sys_expanded ]; then rm /tmp/sys_expanded; else touch /tmp/sys_expanded; fi
format-foreground = ${colors.fg}

[module/wlan]
type = custom/script
exec = ~/.config/polybar/wifi-toggle.sh
interval = 2
click-left = if [ -f /tmp/polybar_wifi_ip ]; then rm /tmp/polybar_wifi_ip; else touch /tmp/polybar_wifi_ip; fi
format-foreground = ${colors.fg}

[module/battery]
type = internal/battery
full-at = 99
battery = BAT0
adapter = ADP1

format-charging = <label-charging>
label-charging = 󰂄  %percentage%%
label-charging-foreground = ${colors.green}

format-discharging = <label-discharging>
label-discharging =   %percentage%%
label-discharging-foreground = ${colors.fg}

format-full = <label-full>
label-full =   100%
label-full-foreground = ${colors.green}
